### PR TITLE
GTH-754: fix crowdfunding test

### LINKED ISSUE #754: Fix Crowdfunding QuickCheck ContractModel failing test case
### Summary

The “Quickcheck ContractModel” test case of Spec.Crowdfunding fails.

There might be other failing test scenarios, but here’s how to reproduce the problem.

### Steps to reproduce the behavior

Add the following test case:

```
testProperty "QuickCheck ContractModel" $ withMaxSuccess 1 $ forAllDL fixedTestCase prop_Crowdfunding`
```

where
```
fixedTestCase = do
    action $ CContribute w6 (Ada.lovelaceValueOf 24991572)
    waitUntilDL (Slot 20)
    action CStart
```

### Actual Result

This logs the following result:
```
  crowdfunding
    QuickCheck ContractModel:                      Expected funds of W[1] to change by
  SymValue {symValMap = fromList [], actualValPart = Value (Map [])}
but they changed by
  SymValue {symValMap = fromList [], actualValPart = Value (Map [(,Map [("",24991572)])])}
a discrepancy of
  SymValue {symValMap = fromList [], actualValPart = Value (Map [(,Map [("",24991572)])])}
Test failed.
Emulator log:
[INFO] Slot 0: TxnValidate b45418acc3c57e0ce8e9f5426ad598dc726b929ded29efffcc40a1b0589ebca7
[INFO] Slot 1: 00000000-0000-4000-8000-000000000000 {Wallet W[1]}:
                 Contract instance started
[INFO] Slot 1: 00000000-0000-4000-8000-000000000001 {Wallet W[2]}:
                 Contract instance started
[INFO] Slot 1: 00000000-0000-4000-8000-000000000002 {Wallet W[3]}:
                 Contract instance started
[INFO] Slot 1: 00000000-0000-4000-8000-000000000003 {Wallet W[4]}:
                 Contract instance started
[INFO] Slot 1: 00000000-0000-4000-8000-000000000004 {Wallet W[5]}:
                 Contract instance started
[INFO] Slot 1: 00000000-0000-4000-8000-000000000005 {Wallet W[6]}:
                 Contract instance started
[INFO] Slot 1: 00000000-0000-4000-8000-000000000006 {Wallet W[7]}:
                 Contract instance started
[INFO] Slot 1: 00000000-0000-4000-8000-000000000007 {Wallet W[8]}:
                 Contract instance started
[INFO] Slot 1: 00000000-0000-4000-8000-000000000008 {Wallet W[9]}:
                 Contract instance started
[INFO] Slot 1: 00000000-0000-4000-8000-000000000009 {Wallet W[10]}:
                 Contract instance started
[INFO] Slot 1: 00000000-0000-4000-8000-000000000005 {Wallet W[6]}:
                 Receive endpoint call on 'contribute' for Object (fromList [("contents",Array [Object (fromList [("getEndpointDescription",String "contribute")]),Object (fromList [("unEndpointValue",Object (fromList [("contribValue
",Object (fromList [("getValue",Array [Array [Object (fromList [("unCurrencySymbol",String "")]),Array [Array [Object (fromList [("unTokenName",String "")]),Number 2.4991572e7]]]])]))]))])]),("tag",String "ExposeEndpointResp")])
[INFO] Slot 1: 00000000-0000-4000-8000-000000000005 {Wallet W[6]}:
                 Contract log: String "Contributing Value (Map [(,Map [(\"\",24991572)])])"
[INFO] Slot 1: W[6]: Balancing an unbalanced transaction:
                       Tx:
                         Tx 5c33eca4cb2676759afffae83838ae7346db480421255b30b037e3a56c82aec8:
                           {inputs:
                           reference inputs:
                           collateral inputs:
                           outputs:
                             - Value (Map [(,Map [("",24991572)])]) addressed to
                               ScriptCredential: dbf5886c23bd2aade401340003b0c45a44d40aab13b18c6f739d6937 (no staking credential)
                               with datum hash 767930fbcd72051f0898e4fa030b75eb2b28ea876c400c9bdd8ff1e67077424d
                               and with no reference script
                           mint: Value (Map [])
                           fee: Value (Map [])
                           mps:
                           signatures:
                           validity range: Interval {ivFrom = LowerBound NegInf True, ivTo = UpperBound (Finite (Slot {getSlot = 20})) False}
                           data:
                             ( 767930fbcd72051f0898e4fa030b75eb2b28ea876c400c9bdd8ff1e67077424d
                             , "\151\173\213\195\202I\NAK4\161\216\DC1e\246\&7\211\&8\224r\212~\198\175\129\NULF<J\GS" )}
                       Requires signatures:
                       Utxo index:
[INFO] Slot 1: W[6]: Finished balancing:
                       Tx 8c70d7f3620dc0669c25c83a14f81655cca2fdf6edfb868cc7008409ec0ebc9a:
                         {inputs:
                            - b45418acc3c57e0ce8e9f5426ad598dc726b929ded29efffcc40a1b0589ebca7!40

                         reference inputs:
                         collateral inputs:
                           - b45418acc3c57e0ce8e9f5426ad598dc726b929ded29efffcc40a1b0589ebca7!40

                         outputs:
                           - Value (Map [(,Map [("",24991572)])]) addressed to
                             ScriptCredential: dbf5886c23bd2aade401340003b0c45a44d40aab13b18c6f739d6937 (no staking credential)
                             with datum hash 767930fbcd72051f0898e4fa030b75eb2b28ea876c400c9bdd8ff1e67077424d
                             and with no reference script
                           - Value (Map [(,Map [("",9999999974831839)])]) addressed to
                             PubKeyCredential: 97add5c3ca491534a1d81165f637d338e072d47ec6af8100463c4a1d (no staking credential)
                             with no datum
                             and with no reference script
                         mint: Value (Map [])
                         fee: Value (Map [(,Map [("",176589)])])
                         validity range: Interval {ivFrom = LowerBound NegInf True, ivTo = UpperBound (Finite (Slot {getSlot = 20})) False}
                         data:
                           ( 767930fbcd72051f0898e4fa030b75eb2b28ea876c400c9bdd8ff1e67077424d
                           , "\151\173\213\195\202I\NAK4\161\216\DC1e\246\&7\211\&8\224r\212~\198\175\129\NULF<J\GS" )
                         redeemers:}
[INFO] Slot 1: W[6]: Signing tx: 8c70d7f3620dc0669c25c83a14f81655cca2fdf6edfb868cc7008409ec0ebc9a
[INFO] Slot 1: W[6]: Submitting tx: 8c70d7f3620dc0669c25c83a14f81655cca2fdf6edfb868cc7008409ec0ebc9a
[INFO] Slot 1: W[6]: TxSubmit: 8c70d7f3620dc0669c25c83a14f81655cca2fdf6edfb868cc7008409ec0ebc9a
[INFO] Slot 1: TxnValidate 8c70d7f3620dc0669c25c83a14f81655cca2fdf6edfb868cc7008409ec0ebc9a
[INFO] Slot 21: 00000000-0000-4000-8000-00000000000a {supercalifragilisticexpialidocious}:
                  Contract instance started
[INFO] Slot 21: 00000000-0000-4000-8000-00000000000a {supercalifragilisticexpialidocious}:
                  Receive endpoint call on 'register-token-env' for Object (fromList [("contents",Array [Object (fromList [("getEndpointDescription",String "register-token-env")]),Object (fromList [("unEndpointValue",Object (fromLis
t [("0",Object (fromList [])),("1",Object (fromList []))]))])]),("tag",String "ExposeEndpointResp")])
[INFO] Slot 21: 00000000-0000-4000-8000-00000000000a {supercalifragilisticexpialidocious}:
                  Contract instance stopped (no errors)
[INFO] Slot 21: 00000000-0000-4000-8000-000000000000 {Wallet W[1]}:
                  Receive endpoint call on 'schedule collection' for Object (fromList [("contents",Array [Object (fromList [("getEndpointDescription",String "schedule collection")]),Object (fromList [("unEndpointValue",Array [])])])
,("tag",String "ExposeEndpointResp")])
[INFO] Slot 21: 00000000-0000-4000-8000-000000000000 {Wallet W[1]}:
                  Contract log: String "Campaign started. Waiting for campaign deadline to collect funds."
[INFO] Slot 21: 00000000-0000-4000-8000-000000000000 {Wallet W[1]}:
                  Contract log: String "Collecting funds"
[INFO] Slot 21: W[1]: Balancing an unbalanced transaction:
                        Tx:
                          Tx 43aa4aab136f3d22abdb6912b657e812ab0e8d4c342a255be565e29fe226826e:
                            {inputs:
                               - 8c70d7f3620dc0669c25c83a14f81655cca2fdf6edfb868cc7008409ec0ebc9a!0
                                 <>
                            reference inputs:
                            collateral inputs:
                            outputs:
                            mint: Value (Map [])
                            fee: Value (Map [])
                            mps:
                            signatures:
                            validity range: Interval {ivFrom = LowerBound (Finite (Slot {getSlot = 20})) True, ivTo = UpperBound (Finite (Slot {getSlot = 29})) False}
                            data:
                              ( 767930fbcd72051f0898e4fa030b75eb2b28ea876c400c9bdd8ff1e67077424d
                              , "\151\173\213\195\202I\NAK4\161\216\DC1e\246\&7\211\&8\224r\212~\198\175\129\NULF<J\GS" )
                            attached scripts:
                              dbf5886c23bd2aade401340003b0c45a44d40aab13b18c6f739d6937}
                        Requires signatures:
                          a2c20c77887ace1cd986193e4e75babd8993cfd56995cd5cfce609c2
                        Utxo index:
                          ( 8c70d7f3620dc0669c25c83a14f81655cca2fdf6edfb868cc7008409ec0ebc9a!0
                          , - Value (Map [(,Map [("",24991572)])]) addressed to
                              ScriptCredential: dbf5886c23bd2aade401340003b0c45a44d40aab13b18c6f739d6937 (no staking credential)
                              with datum hash 767930fbcd72051f0898e4fa030b75eb2b28ea876c400c9bdd8ff1e67077424d
                              and with no reference script )
[INFO] Slot 21: W[1]: Finished balancing:
                        Tx 2f83e47231737b1e0ff74a55722d3d56488e2ce6c66714034942105fa048e84d:
                          {inputs:
                             - 8c70d7f3620dc0669c25c83a14f81655cca2fdf6edfb868cc7008409ec0ebc9a!0

                          reference inputs:
                          collateral inputs:
                            - b45418acc3c57e0ce8e9f5426ad598dc726b929ded29efffcc40a1b0589ebca7!50

                          outputs:
                            - Value (Map [(,Map [("",24652939)])]) addressed to
                              PubKeyCredential: a2c20c77887ace1cd986193e4e75babd8993cfd56995cd5cfce609c2 (no staking credential)
                              with no datum
                              and with no reference script
                          mint: Value (Map [])
                          fee: Value (Map [(,Map [("",338633)])])
                          validity range: Interval {ivFrom = LowerBound (Finite (Slot {getSlot = 20})) True, ivTo = UpperBound (Finite (Slot {getSlot = 29})) False}
                          data:
                          redeemers:}
[INFO] Slot 21: W[1]: Signing tx: 2f83e47231737b1e0ff74a55722d3d56488e2ce6c66714034942105fa048e84d
[INFO] Slot 21: W[1]: Submitting tx: 2f83e47231737b1e0ff74a55722d3d56488e2ce6c66714034942105fa048e84d
[INFO] Slot 21: W[1]: TxSubmit: 2f83e47231737b1e0ff74a55722d3d56488e2ce6c66714034942105fa048e84d
[INFO] Slot 21: 00000000-0000-4000-8000-000000000000 {Wallet W[1]}:
                  Contract instance stopped (no errors)
[INFO] Slot 21: TxnValidate 2f83e47231737b1e0ff74a55722d3d56488e2ce6c66714034942105fa048e84d
FAIL (2.81s)
      *** Failed! Assertion failed (after 1 test):
      DLScript
        [Do $ CContribute (Wallet 6) (Value (Map [(,Map [("",24991572)])])),
         Do $ WaitUntil (Slot {getSlot = 20}),
         Do $ CStart]

      Use --quickcheck-replay=78835 to reproduce.
      Use -p '/QuickCheck ContractModel/' to rerun this test only.
```

### Expected Result

Passing test case. We would also need to make sure that the current property test is working for all actions (`testProperty "QuickCheck ContractModel" $ withMaxSuccess 100 prop_Crowdfunding`)

### Describe the approach you would take to fix this

Note that changing `fixedTestCase` to 

```
fixedTestCase = do
    action $ CContribute w6 (Ada.lovelaceValueOf 24991572)
    waitUntilDL (Slot 20)
    action CStart
    waitUntilDL (Slot 21)
```

solves the issue. However, we fix would probably imply to correctly wait for a transaction to be validated before closing the contract.

### System info

Plutus: 49a3c5abf0a872ad67db7372c1f5b05bc6985acf

### PR DESCRIPTION
**Pull request by sjoerdvisscher**
Fixes #754 

Pre-submit checklist:
- Branch
    - [x] Tests are provided (if possible)
    - [x] Commit sequence broadly makes sense
    - [x] Key commits have useful messages
    - [x] Formatting, PNG optimization, etc. are updated
- PR
    - [x] Self-reviewed the diff
    - [x] Useful pull request description
    - [ ] Reference the ADR in the PR and reference the PR in the ADR (if revelant)
    - [x] Reviewer requested

### CODE REVIEW

File: plutus-use-cases/test/Spec/Crowdfunding.hs [hunk 1]
```diff
@@ -169,9 +169,14 @@ tests = testGroup "crowdfunding"
...
-    -- Re-activate once issue is resolved
-    -- , testProperty "QuickCheck ContractModel" prop_Crowdfunding
+    , testProperty "QuickCheck ContractModel" prop_Crowdfunding
+
+    , testProperty "start-at-slot-20" $ withMaxSuccess 1 $
+        let fixedTestCase = do
+              action $ CContribute w6 (Ada.lovelaceValueOf 20000000)
+              waitUntilDL (Slot 20)
+              action CStart
+        in forAllDL fixedTestCase prop_Crowdfunding
```
Comment (koslambrou) [inline plutus-use-cases/test/Spec/Crowdfunding.hs:179]: Do we want to keep these fixed test cases? They should normally be generated by `testProperty "QuickCheck ContractModel" prop_Crowdfunding`

**Review by koslambrou — APPROVED** [review]

File: plutus-use-cases/test/Spec/Crowdfunding.hs (hunk 1 above)
Comment (sjoerdvisscher) [reply plutus-use-cases/test/Spec/Crowdfunding.hs:179]: This one is pretty tricky, it only fails with exactly slot 20 and no wait at the end. So the chance that QC generates it is pretty small. Otherwise I'd agree.

Comment (koslambrou) [reply plutus-use-cases/test/Spec/Crowdfunding.hs:179]: Good point.
